language: generic
os:
- linux
- osx
matrix:
  exclude:
  - os: osx
    env: CONDA_ENV=lint
  - os: osx
    env: CONDA_ENV=docs
env:
  - CONDA_ENV=py36
  - CONDA_ENV=py37
  - CONDA_ENV=lint
  - CONDA_ENV=docs
  global:
  - secure: "N7EenUcspE/pyC1I+TVLowRIBKPylRC6Jlk/DP4u5GAqIkrLqeZPvTjrWBIMvCkZ2B2dPtUZ5IbbxRMTZCTOQxzlcOL4hbJyzsrRJsskya+Mg9oAFYrZJ6D77AZaQ8iwLgGsOBJsTCyBp9iTBiB3x3KZYUwaMPw3SScVrbNOgzk="
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- |
  if [[ "$CONDA_ENV" == "docs" ]]; then
    conda env create -n test_env --file docs/environment.yml
  else
    conda env create -n test_env --file ci/requirements-$CONDA_ENV.yml
  fi
- source activate test_env
script:
- |
  if [[ "$CONDA_ENV" == "lint" ]]; then
    make lint
  elif [[ "$CONDA_ENV" == "docs" ]]; then
    sphinx-apidoc --force -o docs/api pymt *tests
    make -C docs clean html
  else
    make install
    pytest --cov=pymt --cov-report=xml:$(pwd)/coverage.xml -vvv
  fi
after_success:
  coveralls
